# Generated by Django 4.2.7 on 2023-11-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=100)),
                ("education", models.CharField(max_length=100)),
                ("occupation", models.CharField(max_length=100)),
                ("comments", models.TextField()),
                ("question", models.CharField(max_length=255)),
                ("answer", models.CharField(max_length=255)),
                ("time_taken", models.FloatField()),
                ("session_id", models.UUIDField()),
            ],
        ),
    ]
