# Generated by Django 4.2.7 on 2023-11-26 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_remove_userresponse_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresponse",
            name="session_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
