# Generated by Django 3.2.10 on 2023-11-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userresponse_session_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
