# Generated by Django 3.2.10 on 2023-11-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_demographics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographics',
            name='id',
        ),
        migrations.AddField(
            model_name='demographics',
            name='session_id',
            field=models.UUIDField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
