# Generated by Django 3.2.10 on 2023-11-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20231129_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographics',
            name='responses',
            field=models.JSONField(default=list),
        ),
    ]
