# Generated by Django 3.2.10 on 2023-11-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_demographics_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographics',
            name='responses',
        ),
    ]
