# Generated by Django 3.2.10 on 2023-12-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_demographics_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='time_taken',
            field=models.TextField(blank=True),
        ),
    ]
