# Generated by Django 3.2.10 on 2023-12-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_demographics_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographics',
            name='is_correct',
            field=models.TextField(blank=True),
        ),
    ]
