# Generated by Django 3.2.10 on 2023-12-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_demographics_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographics',
            name='education',
        ),
        migrations.RemoveField(
            model_name='demographics',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='demographics',
            name='occupation',
        ),
        migrations.AlterField(
            model_name='demographics',
            name='experience',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=20),
        ),
    ]
